pygments: true
permalink: /articles/:title
navigation:
- text: <img src="/images/logo.png"/><span>Anthony Garand</span>
  url: /
  shortname: index
- text: Articles
  url: /articles
  shortname: articles
- text: Recent Work
  url: /work
  shortname: work
- text: About
  url: /about
  shortname: about
- text: Contact
  url: mailto:anthonygarand@gmail.com
  shortname: contact